### ISSUE TITLE
NameError: name 'height' is not defined

### ISSUE THREAD

**Issue by CodingPenguin** [kevinjycui/DesmosBezierRenderer#26]
Error when running backend.py and then entering f = 1 in the formula field (in the index.html). Here's the error traceback (500 error):
`[2021-07-04 19:20:40,644] ERROR in app: Exception on /init [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/codingdanny/projects/fun/DesmosBezierRenderer/backend.py", line 141, in init
    return json.dumps({'height': height.value, 'width': width.value, 'total_frames': len(os.listdir(FRAME_DIR)), 'download_images': DOWNLOAD_IMAGES, 'show_grid': SHOW_GRID})
NameError: name 'height' is not defined
127.0.0.1 - - [04/Jul/2021 19:20:40] "GET /init HTTP/1.1" 500 -`

**Comment by cartesiancanvas** [comment]
Same.I dont know how to fix it.

**Comment by geubsig** [comment]
Same... I also don't know the solution which is freaking me out

**Comment by kevinjycui** [comment]
I am unable to replicate this error, but if anyone encounters this error again please let me know here. I pushed a commit that might resolve the issue as I believe the issue could be potentially stemming from the app being run before the processing could finish.

**Comment by kevinjycui** [comment]
Closing this issue due to inactivity. Please re-open in the case that the error resurfaces.
