### ISSUE TITLE
Issue in backend.py usind .bmp images

### ISSUE THREAD

**Issue by Maxxxutko** [kevinjycui/DesmosBezierRenderer#38]
Full error traceback:

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "backend.py", line 118, in get_expressions
    for expr in get_latex(FRAME_DIR + '/frame%d.%s' % (frame+1, FILE_EXT)):
  File "backend.py", line 92, in get_latex
    path = get_trace(get_contours(filename))
  File "backend.py", line 62, in get_contours
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-ms668fyv/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "backend.py", line 208, in <module>
    frame_latex = pool.map(get_expressions, frame_latex)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-ms668fyv/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

_**Instead of using png images I'd used bmp images. In backend.py I changed value of File_Exit = bmp and wrote down full path to frame folder in Frame_Dir. Excuse me for my bad English, hope that somebody can help me with my problem**_

**Comment by Maxxxutko** [comment]
@kevinjycui

**Comment by kevinjycui** [comment]
Have you tried checking everything in the response to #27 ?

**Comment by Maxxxutko** [comment]
I

> Have you tried checking everything in the response to #27 ?

I'm running all processes in su mode, I mentioned full path to the frame folder in backend.py. Can it be due to using .bmp files?

**Comment by kevinjycui** [comment]
.bmp files should be fine, considering the program converts the image into a bitmap even if it isn't in .bmp

**Comment by Maxxxutko** [comment]
If I understood it correctly, I don't need to write equation in LATex?

**Comment by kevinjycui** [comment]
Sorry, I'm a bit confused about this question. Are you following the instructions on the README? The program converts an image to LaTeX expressions. You do not need to write anything in LaTeX yourself.

**Comment by kevinjycui** [comment]
Closing due to inactivity. Though it might help to see a similar issue #39
