### ISSUE TITLE
ERROR: Could not build wheels for pypotrace which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by BabyBoy666** [kevinjycui/DesmosBezierRenderer#4]
The issue arises when I do `pip install -r requirements.txt`(note pip3 returns same results) the full results are:
```
Requirement already satisfied: click==7.1.2 in /opt/virtualenvs/python3/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (7.1.2)
Requirement already satisfied: cycler==0.10.0 in /opt/virtualenvs/python3/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (0.10.0)
Requirement already satisfied: Flask==1.1.2 in /opt/virtualenvs/python3/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (1.1.2)
Collecting Flask-Cors==3.0.10
  Using cached Flask_Cors-3.0.10-py2.py3-none-any.whl (14 kB)
Requirement already satisfied: itsdangerous==1.1.0 in /opt/virtualenvs/python3/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (1.1.0)
Requirement already satisfied: Jinja2==2.11.3 in /opt/virtualenvs/python3/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (2.11.3)
Requirement already satisfied: kiwisolver==1.3.1 in /opt/virtualenvs/python3/lib/python3.8/site-packages (from -r requirements.txt (line 7)) (1.3.1)
Requirement already satisfied: MarkupSafe==1.1.1 in /opt/virtualenvs/python3/lib/python3.8/site-packages (from -r requirements.txt (line 8)) (1.1.1)
Requirement already satisfied: matplotlib==3.4.1 in /opt/virtualenvs/python3/lib/python3.8/site-packages (from -r requirements.txt (line 9)) (3.4.1)
Requirement already satisfied: numpy==1.20.2 in /opt/virtualenvs/python3/lib/python3.8/site-packages (from -r requirements.txt (line 10)) (1.20.2)
Collecting opencv-python==4.5.1.48
  Using cached opencv_python-4.5.1.48-cp38-cp38-manylinux2014_x86_64.whl (50.4 MB)
Requirement already satisfied: Pillow==8.2.0 in /opt/virtualenvs/python3/lib/python3.8/site-packages (from -r requirements.txt (line 12)) (8.2.0)
Requirement already satisfied: pyparsing==2.4.7 in /opt/virtualenvs/python3/lib/python3.8/site-packages (from -r requirements.txt (line 13)) (2.4.7)
Collecting pypotrace==0.3
  Using cached pypotrace-0.3.tar.gz (11 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: python-dateutil==2.8.1 in /opt/virtualenvs/python3/lib/python3.8/site-packages (from -r requirements.txt (line 15)) (2.8.1)
Requirement already satisfied: six==1.15.0 in /opt/virtualenvs/python3/lib/python3.8/site-packages (from -r requirements.txt (line 16)) (1.15.0)
Requirement already satisfied: Werkzeug==1.0.1 in /opt/virtualenvs/python3/lib/python3.8/site-packages (from -r requirements.txt (line 17)) (1.0.1)
Building wheels for collected packages: pypotrace
  Building wheel for pypotrace (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/virtualenvs/python3/bin/python3 /opt/virtualenvs/python3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpj5jn8i1v
       cwd: /tmp/pip-install-ijqkzuo5/pypotrace_e778e9c007494dd781d506bbbd0e5d10
  Complete output (37 lines):
  A setup.py file already exists. Using it.
  Package libagg was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libagg.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libagg' found
  Traceback (most recent call last):
    File "/tmp/pip-install-ijqkzuo5/pypotrace_e778e9c007494dd781d506bbbd0e5d10/setup.py", line 28, in <module>
      build(setup_kwargs)
    File "/tmp/pip-install-ijqkzuo5/pypotrace_e778e9c007494dd781d506bbbd0e5d10/build.py", line 19, in build
      extra_compile_args = pkg_config("libagg", '--cflags')
    File "/tmp/pip-install-ijqkzuo5/pypotrace_e778e9c007494dd781d506bbbd0e5d10/build.py", line 11, in pkg_config
      return subprocess.check_output(["pkg-config", command, pkg_name]).decode(
    File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/usr/lib/python3.8/subprocess.py", line 516, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['pkg-config', '--cflags', 'libagg']' returned non-zero exit status 1.
  Traceback (most recent call last):
    File "/opt/virtualenvs/python3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 280, in <module>
      main()
    File "/opt/virtualenvs/python3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/opt/virtualenvs/python3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-bkf4597c/overlay/lib/python3.8/site-packages/poetry/core/masonry/api.py", line 68, in build_wheel
      return unicode(WheelBuilder.make_in(poetry, Path(wheel_directory)))
    File "/tmp/pip-build-env-bkf4597c/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 72, in make_in
      wb.build()
    File "/tmp/pip-build-env-bkf4597c/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 103, in build
      self._build(zip_file)
    File "/tmp/pip-build-env-bkf4597c/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 135, in _build
      self._run_build_command(setup)
    File "/tmp/pip-build-env-bkf4597c/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 163, in _run_build_command
      subprocess.check_call(
    File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/opt/virtualenvs/python3/bin/python3', '/tmp/pip-install-ijqkzuo5/pypotrace_e778e9c007494dd781d506bbbd0e5d10/setup.py', 'build', '-b', '/tmp/pip-install-ijqkzuo5/pypotrace_e778e9c007494dd781d506bbbd0e5d10/build']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for pypotrace
Failed to build pypotrace
ERROR: Could not build wheels for pypotrace which use PEP 517 and cannot be installed directly
```
I've tried stuff I've found including
updating pip3/pip
`
pip install p5py
pip install PEP517
`
`
pip install --upgrade pip setuptools wheel
`
and a few others i don't remember

Any help is appreciated!

*Note: i don't have much experience with pip

**Comment by kevinjycui** [comment]
I forgot to add the potrace dependencies in the setup instructions. See 47b10ea98b04b98ce46e54a46adde27bcb52e53e for the fix

**Comment by BabyBoy666** [comment]
ok that worked and I installed potrace but when i ran backend.py it came up with a new error
```
Traceback (most recent call last):
  File "backend.py", line 77, in <module>
    frame_latex.append(get_latex(FRAME_DIR + '/frame%d.png' % (i+1)))
  File "backend.py", line 51, in get_latex
    path = get_trace(get_contours(filename))
  File "backend.py", line 29, in get_contours
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-ms668fyv/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
```

**Comment by ayushdiagarwal** [comment]
I'm getting the same error on macos and is unable to install the packages @kevinjycui wrote in the dependencies. How do I solve this issue?
