### ISSUE TITLE
Unable to process file

### ISSUE THREAD

**Issue by sunshade1220** [kevinjycui/DesmosBezierRenderer#41]
I followed the instructions and replaced all the original frames in the frames directory with a frame1.png file.
And I got an error
```
Processing 1 frames... Please wait for processing to finish before running on frontend

[ERROR] Unable to process one or more files. Remember image files should be named <DIRECTORY>/frame<INDEX>.<EXTENSION> where INDEX represents the frame number starting from 1 and DIRECTORY and EXTENSION are defined by command line arguments (e.g. frames/frame1.png). Please check if:
        The files exist
        The files are all valid image files
        The name of the files given is correct as per command line arguments
        The program has the necessary permissions to read the file.

Use backend.py -h for further documentation
-----------------------------
Full error traceback:

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "backend.py", line 118, in get_expressions
    for expr in get_latex(FRAME_DIR + '/frame%d.%s' % (frame+1, FILE_EXT)):
  File "backend.py", line 92, in get_latex
    path = get_trace(get_contours(filename))
  File "backend.py", line 62, in get_contours
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "backend.py", line 208, in <module>
    frame_latex = pool.map(get_expressions, frame_latex)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
```
I still got the same error when I put back the original files (I saved them just in case)

**Comment by sunshade1220** [comment]
solved using `chmod 755 *` in frames directory
