### ISSUE TITLE
Backend error

### ISSUE THREAD

**Issue by chenyichie** [kevinjycui/DesmosBezierRenderer#46]
I'm using wsl and running the command "python3 backend.py". and I get this error:

Desmos Bezier Renderer
Junferno 2021
https://github.com/kevinjycui/DesmosBezierRenderer
-----------------------------
Processing 513 frames... Please wait for processing to finish before running on frontend

--> Processing complete in 6.9 seconds

 * Serving Flask app "backend" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [29/Jul/2022 16:48:50] "GET /init HTTP/1.1" 200 -
[2022-07-29 16:48:59,070] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/DesmosBezierRenderer/env/lib/python3.10/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/DesmosBezierRenderer/env/lib/python3.10/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/DesmosBezierRenderer/env/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/user/DesmosBezierRenderer/env/lib/python3.10/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/DesmosBezierRenderer/env/lib/python3.10/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/DesmosBezierRenderer/env/lib/python3.10/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/DesmosBezierRenderer/env/lib/python3.10/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/DesmosBezierRenderer/backend.py", line 126, in index
    frame = int(request.args.get('frame'))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by kevinjycui** [comment]
It seems like it's making a call to the backend without specifying the frame. How are you running the front-end? Are you using index.html or quick.html?

**Comment by chenyichie** [comment]
I use index.html, and I wait a long time and then get this error.

**Comment by braxton092408** [comment]
I have this same issue

**Comment by jiahuiiiii** [comment]
hey I'm facing the same issue. Did you get the problem solved?
