### ISSUE TITLE
request.args.get('frame') returning NoneType?

### ISSUE THREAD

**Issue by aunDominic** [kevinjycui/DesmosBezierRenderer#6]
```
Traceback (most recent call last):
  File "/home/dominic/DesmosBezierRenderer/env/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/dominic/DesmosBezierRenderer/env/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/dominic/DesmosBezierRenderer/env/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/dominic/DesmosBezierRenderer/env/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dominic/DesmosBezierRenderer/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dominic/DesmosBezierRenderer/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dominic/DesmosBezierRenderer/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dominic/DesmosBezierRenderer/env/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/dominic/DesmosBezierRenderer/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dominic/DesmosBezierRenderer/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dominic/DesmosBezierRenderer/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dominic/DesmosBezierRenderer/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dominic/DesmosBezierRenderer/backend.py", line 96, in index
    frame = int(request.args.get('frame'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
I assume ```request.args.get('frame')``` is returning a NoneType , since int( ) is getting a TypeError.

Could it be that I named my files wrongly? 
I created the ```frames``` directory and inside ```frames``` i added a file ```frame1.png```.

my directory: 
* DesmosBezierRenderer
   * frames
      * frame1.png
   * desmos
   * env
   * github
   * backend.py
   * index.html
   * requirements.txt

**Comment by kevinjycui** [comment]
`request.args.get('frame')` should be referring to the request in the URL from the frontend to the backend. How are you rendering the image? Are you setting frame=1 in the sidebar of Desmos?

**Comment by aunDominic** [comment]
oh yeah that was the problem aaa
