### ISSUE TITLE
backend error - even though the frames are labeled correctly it comes up with theses errors

### ISSUE THREAD

**Issue by cyberhero23** [kevinjycui/DesmosBezierRenderer#60]
[ WARN:0@9.132] global loadsave.cpp:244 findDecoder imread_('frames/frame1.png'): can't open/read file: check file path/integrity
[ WARN:0@9.132] global loadsave.cpp:244 findDecoder imread_('frames/frame7.png'): can't open/read file: check file path/integrity
[ WARN:0@9.132] global loadsave.cpp:244 findDecoder imread_('frames/frame13.png'): can't open/read file: check file path/integrity
[ WARN:0@9.132] global loadsave.cpp:244 findDecoder imread_('frames/frame19.png'): can't open/read file: check file path/integrity
[ WARN:0@9.135] global loadsave.cpp:244 findDecoder imread_('frames/frame25.png'): can't open/read file: check file path/integrity
[ WARN:0@9.135] global loadsave.cpp:244 findDecoder imread_('frames/frame31.png'): can't open/read file: check file path/integrity
[ WARN:0@9.135] global loadsave.cpp:244 findDecoder imread_('frames/frame37.png'): can't open/read file: check file path/integrity
[ WARN:0@9.136] global loadsave.cpp:244 findDecoder imread_('frames/frame43.png'): can't open/read file: check file path/integrity
[ WARN:0@9.136] global loadsave.cpp:244 findDecoder imread_('frames/frame49.png'): can't open/read file: check file path/integrity
[ WARN:0@9.139] global loadsave.cpp:244 findDecoder imread_('frames/frame55.png'): can't open/read file: check file path/integrity
[ WARN:0@9.141] global loadsave.cpp:244 findDecoder imread_('frames/frame61.png'): can't open/read file: check file path/integrity
[ WARN:0@9.144] global loadsave.cpp:244 findDecoder imread_('frames/frame67.png'): can't open/read file: check file path/integrity
[ WARN:0@9.145] global loadsave.cpp:244 findDecoder imread_('frames/frame79.png'): can't open/read file: check file path/integrity
[ WARN:0@9.148] global loadsave.cpp:244 findDecoder imread_('frames/frame85.png'): can't open/read file: check file path/integrity
[ WARN:0@9.149] global loadsave.cpp:244 findDecoder imread_('frames/frame91.png'): can't open/read file: check file path/integrity
[ WARN:0@9.151] global loadsave.cpp:244 findDecoder imread_('frames/frame73.png'): can't open/read file: check file path/integrity
[ERROR] Unable to process one or more files. Remember image files should be named <DIRECTORY>/frame<INDEX>.<EXTENSION> where INDEX represents the frame number starting from 1 and DIRECTORY and EXTENSION are defined by command line arguments (e.g. frames/frame1.png). Please check if:
        The files exist
        The files are all valid image files
        The name of the files given is correct as per command line arguments
        The program has the necessary permissions to read the file.

Use backend.py -h for further documentation

-----------------------------
Full error traceback:

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/wsl/DesmosBezierRenderer/backend.py", line 120, in get_expressions
    for expr in get_latex(FRAME_DIR + '/frame%d.%s' % (frame+1, FILE_EXT)):
  File "/home/wsl/DesmosBezierRenderer/backend.py", line 94, in get_latex
    path = get_trace(get_contours(filename))
  File "/home/wsl/DesmosBezierRenderer/backend.py", line 64, in get_contours
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.7.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wsl/DesmosBezierRenderer/backend.py", line 234, in <module>
    frame_latex = pool.map(get_expressions, frame_latex)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
cv2.error: OpenCV(4.7.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

**Comment by Vistaminc** [comment]
mee too, do you solve it?

**Comment by cybr23** [comment]
> mee too, do you solve it?

I gave up

**Comment by waterblah123** [comment]
lmk if anyone solves

**Comment by waterblah123** [comment]
fix: add more than 1 frame
