### ISSUE TITLE
problem; unab;e to process one or more file

### ISSUE THREAD

**Issue by lethalyrael** [kevinjycui/DesmosBezierRenderer#76]
[ WARN:0@1.469] global loadsave.cpp:241 findDecoder imread_('frames/frame2.png'): can't open/read file: check file path/integrity
--> Frame 1/2[ERROR] Unable to process one or more files. Remember image files should be named <DIRECTORY>/frame<INDEX>.<EXTENSION> where INDEX represents the frame number starting from 1 and DIRECTORY and EXTENSION are defined by command line arguments (e.g. frames/frame1.png). Please check if:
        The files exist
        The files are all valid image files
        The name of the files given is correct as per command line arguments
        The program has the necessary permissions to read the file.

Use backend.py -h for further documentation

-----------------------------
Full error traceback:

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "/home/****/DesmosBezierRenderer/backend.py", line 121, in get_expressions
    for expr in get_latex(FRAME_DIR + '/frame%d.%s' % (frame+1, FILE_EXT)):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/****/DesmosBezierRenderer/backend.py", line 95, in get_latex
    path = get_trace(get_contours(filename))
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/****/DesmosBezierRenderer/backend.py", line 65, in get_contours
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.10.0) /io/opencv/modules/imgproc/src/color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/****/DesmosBezierRenderer/backend.py", line 226, in <module>
    frame_latex = pool.map(get_expressions, frame_latex)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/pool.py", line 774, in get
    raise self._value
cv2.error: OpenCV(4.10.0) /io/opencv/modules/imgproc/src/color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

**Comment by MikeChen012345** [comment]
I figured out what the issue is just now: use the Ubuntu command line to check if there are some hidden files that end with `Zone.Identifier` in the `frames` directory. Removing them and the code will work.
![image](https://github.com/user-attachments/assets/0e209067-ab2b-4e5f-a078-1eb845a9ff9c)
